config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, :presence => true
  validates :id_number, :presence => true,
                        :length => { is: 2 }
  validates :started_at, :presence => true

  has_many :courses_user
  has_and_belongs_to_many :users
end

app/models/courses_user.rb
class CoursesUser < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses_user
  has_and_belongs_to_many :courses

  def major_course
    result = self.courses_user.find_by(is_major: true)
    raise "User cannot without major course" if result.blank?
    result.course
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @users = @course.users.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :id_number, :started_at)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @course = Course.find(params[:course][:id])
    @user = User.new(user_params)

    # FIXME: 僧眾的代碼
    # FIXME  這一段邏輯可能要放到model
    id_number = String.new
    id_number[0] = @user.utype == '在家' ? 'G' : 'N'
    id_number[1] = @user.sex == '男' ? 'M' : 'F'
    id_number[2..5] = Date.current.year.to_s
    id_number[6..7] = @course.id_number.to_s
    id_number << (@course.users.count + 1).to_s
    @user.id_number = id_number

    @user.courses << @course
    respond_to do |format|
      if @user.save
        cu_relation = CoursesUser.find_by(user_id: @user.id, course_id: @course.id)
        cu_relation.is_major = true
        cu_relation.save

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:last_name, :first_name, :id_number, :sex, :cellphone_number, :email, :utype, :line_account, :line_name, :buddhism_exp, :skills)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :id_number %>
    <%= form.text_field :id_number %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.date_select :started_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Started at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.id_number %></td>
        <td><%= course.name %></td>
        <td><%= course.started_at %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @course.started_at %>
</p>

<table>
  <thead>
    <tr>
      <th>學號</th>
      <th>姓名</th>
      <th>性別</th>
      <th>手機號碼</th>
      <th>Email</th>
      <th>身份</th>
      <th>Line帳號</th>
      <th>Line暱稱</th>
      <th colspan="3">控制</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id_number %></td>
        <td><%= user.last_name %><%= user.first_name %></td>
        <td><%= user.sex %></td>
        <td><%= user.cellphone_number %></td>
        <td><%= user.email %></td>
        <td><%= user.utype %></td>
        <td><%= user.line_account %></td>
        <td><%= user.line_name %></td>
        <td><%= link_to '顯示', user %></td>
        <td><%= link_to '編輯', edit_user_path(user) %></td>
        <td><%= link_to '刪除', user, method: :delete, data: { confirm: '確定要刪除嗎?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to '新增學員', new_user_path(course_id: @course.id) %>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless user.persisted? # new page %>
    <%= hidden_field :course, :id, value: params[:course_id] %>
  <% end %>

  <% if user.persisted? # edit page %>
  <div class="field">
    <%= form.label :id_number, "學號" %>
    <%= user.id_number %>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name, "姓" %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name, "名" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :sex, "性別" %>
    <%= form.select :sex, ['男', '女']%>
  </div>

  <div class="field">
    <%= form.label :cellphone_number, "手機號碼" %>
    <%= form.text_field :cellphone_number %>
  </div>

  <div class="field">
    <%= form.label :email, "Email" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :utype, "身份" %>
    <%= form.select :utype, ['在家', '僧眾']%>
  </div>

  <div class="field">
    <%= form.label :line_account, "Line帳號" %>
    <%= form.text_field :line_account %>
  </div>

  <div class="field">
    <%= form.label :line_name, "Line暱稱" %>
    <%= form.text_field :line_name %>
  </div>

  <div class="field">
    <%= form.label :buddhism_exp %>
    <%= form.text_area :buddhism_exp %>
  </div>

  <div class="field">
    <%= form.label :skills %>
    <%= form.text_area :skills %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>學員</h1>

<table>
  <thead>
    <tr>
      <th>學號</th>
      <th>姓名</th>
      <th>性別</th>
      <th>手機號碼</th>
      <th>Email</th>
      <th>身份</th>
      <th>Line帳號</th>
      <th>Line暱稱</th>
      <th colspan="3">控制</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id_number %></td>
        <td><%= user.last_name %><%= user.first_name %></td>
        <td><%= user.sex %></td>
        <td><%= user.cellphone_number %></td>
        <td><%= user.email %></td>
        <td><%= user.utype %></td>
        <td><%= user.line_account %></td>
        <td><%= user.line_name %></td>
        <td><%= link_to '顯示', user %></td>
        <td><%= link_to '編輯', edit_user_path(user) %></td>
        <td><%= link_to '刪除', user, method: :delete, data: { confirm: '確定要刪除嗎?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增學員', new_user_path(course_id: params[:course_id]) %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @user.id_number %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<p>
  <strong>Cellphone number:</strong>
  <%= @user.cellphone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Utype:</strong>
  <%= @user.utype %>
</p>

<p>
  <strong>Line account:</strong>
  <%= @user.line_account %>
</p>

<p>
  <strong>Line name:</strong>
  <%= @user.line_name %>
</p>

<p>
  <strong>Buddhism exp:</strong>
  <%= @user.buddhism_exp %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @user.skills %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to '回學員清單', users_path %>

 <!-- TODO -->
<%#= link_to '' course_path(@user.courses.first)%>